[package]
name = "yoroolbot"
version = "0.1.0"
edition = "2024"

[lib]
name = "yoroolbot"
path = "src/lib.rs"

[dependencies]
teloxide = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }