[package]
name = "ledgerbot"
edition = "2024"
version =  { workspace = true }

[[bin]]
name = "ledgerbot"
path = "src/main.rs"

[dependencies]
teloxide = { workspace = true }
telluride = { workspace = true }
log = { workspace = true }
pretty_env_logger = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
rust_decimal = { workspace = true }
yoroolbot = { path = "../yoroolbot" }